### ISSUE TITLE
[Feature Request] Rift

### ISSUE THREAD

**Issue by ghost** [Twentysix26/26-Cogs#13]
- Ability to have the bot show usernames on both sides of the rift.

- Ability to have each rift associated with an ID therefore rifts can be closed individually if linked from the same channel and also means it's less prone to accidental closure. (A list with channels associated with IDs would also be needed)

**Comment by KingJaffa** [comment]
I too would love this feature

**Comment by 6sc** [comment]
I was coming here to suggest the same thing. Would be nice.

**Comment by NNTin** [comment]
The current rift does not relay all messages from one side to another. It only allows the original author (from source to destionation, destination to source works fine). This can be good if the bot owner likes to send messages through the bot. If this is the case the command should only be limited to the owner (or roles with sufficient rights).
Alternatively make the rift work both way always. So all messages are sent from source to destination (not the author only).
Instead of sending a normal message, send an embed message. The benefit is you can include an author icon as well as @mention people without creating a notification. So it is easier to see the origin of the message without self-pinging yourself everytime you make a message.
