### ISSUE TITLE
Have remind me give reminders? 

### ISSUE THREAD

**Issue by suedeyoung** [Twentysix26/26-Cogs#43]
Hey guys! 

I'm not sure if this is possible, it seems like that the coding for Remindme may have something like a check if you do !forgetme but it doesn't seem to have a !check_reminders or anything like that (from what I can tell.) 

Some users on my discord wanted to have it possible to where if they set something long (such as a few days or for some reason one user did a year) that it will give them output on what their reminders are. 

Is there anything like that that I'm may be missing?

**Comment by AutumnClove** [comment]
I'm two years late, and I don't even know if this is still a working bot, however I did make a feature like that on a bot, which takes from reminders from here(ofc gives source info though!) You can see what I did here: 
https://github.com/AutumnClove/aleBot/blob/pre-cog-update/mods/reminders.py#L85

**Comment by Twentysix26** [comment]
@AutumnClove The bot is alive, this repo not so much since it's for Red V2 and the current version is V3. The remindme cog has been ported to the current version and you can find it in [this repo](https://github.com/PhasecoreX/PCXCogs). You can find my V3 repo [here](https://github.com/Twentysix26/x26-Cogs)
